# SPDX-FileCopyrightText: The ansible-wrapper Authors
# SPDX-License-Identifier: 0BSD

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - sebhoss
